### ISSUE TITLE
app.js not grabbing outports from correct JS object 

### ISSUE THREAD

**Issue by hypergrace** [Cycling74/rnbo.example.webpage#10]
Hi all, I found strange behavior where outports were not being grabbed from the RNBO export. Looking at app.js, 

I found that `function attachOutports` was looking to "device" for an "outports" property, where as the "outports" property is contained in the "patcher" object. 

I made the following changes to `function attachoutPorts`

```
function attachOutports(device, patcher) {
  const outports = patcher.desc.outports;
  if (outports.length < 1) {
    document
      .getElementById("rnbo-console")
      .removeChild(document.getElementById("rnbo-console-div"));
    return;
  }
...
}
```

and naturally amended line 91 where the function is called to pass in both patcher and device. 

```
  // (Optional) Attach listeners to outports so you can log messages from the RNBO patcher
  attachOutports(device, patcher);
```

**Comment by fde31** [comment]
AFAIK `device.outports` is a recent addition to the API and was introduced with RNBO v1.1.0.

Before looking more into it - Is it possible that you running a RNBO version older that that?

**Comment by hypergrace** [comment]
Aha, that's the rub. My apologies for that oversight!

**Comment by fde31** [comment]
No worries! Glad that solved it. Thanks!
