### ISSUE TITLE
Parsing Typescript patch into corresponding interface

### ISSUE THREAD

**Issue by ammlyy** [Cycling74/rnbo.example.webpage#11]
Hello everyone,

I'm trying to include a patch inside a Typescript project.
Adding resolveJsonModule as stated in the [Working with TS](https://rnbo.cycling74.com/learn/working-with-typescript) tutorial, I'm able to load it and access its parameters.
I'm having troubles in initializing the IPatcher instance, as I'm not able to cast the imported JSON to the correct interface.
Any tips?
Thanks in advance.

**Comment by benbrackenc74** [comment]
@ammlyy Can you attach/link to a simple project and the steps you are going through?

**Comment by starakaj** [comment]
Hey @ammlyy, I tried the following:

```ts
import { createDevice, IPatcher } from "@rnbo/js";

let patcher: IPatcher;
let context: AudioContext;

context = new AudioContext();

patcher = JSON.parse("a json string representing an actual patch I promise");

async function myfunc() {
    const device = await createDevice({
        patcher: patcher,
        context: context
    });
}
``` 

and the TypeScript compiler seems to be happy with it. Could you attach a project or a code snippet?

**Comment by ammlyy** [comment]
Hello @starakaj  sorry for the late response!

At first, I was using the import statement to include the JSON file, something like

`import patch from '../rnbo/patch.export.json';`

I managed to make it work importing the JSON directly as you did in your example.
