### ISSUE TITLE
naming conflicts present issues for param sliders if patcher contains multiple instances of an abstraction

### ISSUE THREAD

**Issue by jinpavg** [Cycling74/rnbo.example.webpage#7]
When using an abstraction ([p @file filename]) multiple times, if the abstraction has a parameter in it, this example's UI sliders for those parameters are buggy.

https://github.com/Cycling74/rnbo.example.webpage/blob/88f5fb06e4bafb7a55afe84a7e94aab14bf24a5d/js/app.js#L197-L207

if `param.name` is replaced by `param.id`, the sliders no longer conflict.

**Comment by starakaj** [comment]
yup yup, I can fix this

**Comment by starakaj** [comment]
Fixed?

**Comment by jinpavg** [comment]
~lookin good~
